---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-deployment
  labels:
    app: nop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nop
  template:
    metadata:
      labels:
        app: nop
    spec:
      containers:
      - name: nop
        image: panky7700/nop-test-terraform:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nop-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nop